USE_CAMERA_STUB := false

TARGET_BOOTLOADER_BOARD_NAME := paso
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOARD_PLATFORM := msm7x30
TARGET_CPU_ABI  := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon

BOARD_KERNEL_CMDLINE := console=null
BOARD_KERNEL_BASE := 0x20000000
BOARD_KERNEL_PAGESIZE := 4096

BOARD_BOOTIMAGE_PARTITION_SIZE     := 0x00500000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
BOARD_SYSTEMIMAGE_PARTITION_SIZE   := 0x0c640000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0b900000
BOARD_FLASH_BLOCK_SIZE := 4096

TARGET_PREBUILT_KERNEL := device/acer/paso/kernel

BOARD_SDCARD_INTERNAL_DEVICE := /dev/block/mmcblk0p1

TARGET_RECOVERY_PRE_COMMAND := "touch /cache/recovery/boot;sync;"
BOARD_HAS_SMALL_RECOVERY := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_USES_RECOVERY_CHARGEMODE := false
BOARD_CUSTOM_GRAPHICS := ../../../device/acer/paso/recovery/graphics.c
BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/acer/paso/recovery/recovery_ui.c
